- README.md
Fixes badges and links in the README.md file, and add a few new ones.
> chore: fix readme relative links

- CHANGELOG.md
- src/Type/WPObject/LoginOptions.php
- chore: Update doc-block header in `src/Type/WPObject/LoginOptions.php`
https://codeclimate.com/github/AxeWP/wp-graphql-headless-login/src/Type/WPObject/ClientOptions.php/source#issue-6078ddcaf4b7c012af9b262eba9f5233
> chore: update header doc-block description

- CHANGELOG.md
- src/Auth/ProviderConfig/OAuth2/Google.php
- tests/wpunit/GithubProviderMutationsTest.php
- tests/wpunit/GoogleProviderMutationsTest.php
- vendor/composer/installed.php
Adds mutation tests for Github and Google providers, fixing bugs along the way.
- fix: Correctly map Github first and last name to user data.
- tests: add tests for Github and Google provider mutations.
> tests: add provider mutation tests

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-headless-login.php
> release: 0.0.2

- README.md
- readme.txt
Fixes a few typos in README.md and readme.txt
> chore: fix readme typos

- .github/workflows/integration-testing.yml
- .github/workflows/schema-linter.yml
Updates Schema Linter workflow to use `actions/setup-node@v3`
Node v12 is deprecated.
> ci: update actions/setup-node to v3

- CHANGELOG.md
- composer.json
- composer.lock
- vendor/composer/installed.php
Updates composer deps (including Strauss) to latest versions.
Also backfiles missing changelog entries.
Housekeeping
> chore: update Composer deps

- CHANGELOG.md
- README.md
- package.json
- phpstan/constants.php
- readme.txt
- src/Auth/ProviderConfig/OAuth2/Instagram.php
- src/Auth/ProviderConfig/OAuth2/LinkedIn.php
- vendor/composer/installed.php
- wp-graphql-headless-login.php
> Release: v0.0.3

- .github/workflows/code-quality.yml
- .github/workflows/code-standard.yml
- .github/workflows/integration-testing.yml
- .github/workflows/schema-linter.yml
- CHANGELOG.md
- docker/app.Dockerfile
Update GitHub workflows to latest versions. Additionally fixes an issue where Docker is unable to install XDebug on PHP 7.x.
> ci: update workflows

- README.md
Fixes the ci badges in readme.md
> chore: fix repo CI badges

- CHANGELOG.md
- README.md
- bin/_lib.sh
- composer.json
- composer.lock
- docs/example-next-api-routes.md
- docs/mutations.md
- docs/queries.md
- docs/usage.md
- phpstan.neon.dist
- src/Main.php
- src/WoocommerceSchemaFilters.php
- tests/functional.suite.dist.yml
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
- vendor/composer/installed.php
This PR adds support for [WPGraphQL for WooCommerce](https://github.com/wp-graphql/wp-graphql-woocommerce)
Woo uses a special `woocommerce-session` header that needs to be managed, but the extension [only includes a shim for WPGraphQL JWT Authentication](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/class-jwt-auth-schema-filters.php)
If WPGraphQL for WooCommerce is detected, 
- `wooSessionToken` will be available on `AuthenticationData`, and the `LoginPayload`/`LoginWithPasswordPayload`.
- `AuthenticationData` will be available on `Customer.auth`.
- `Customer` will be available on `Login{?WithPassword}Payload.customer`.
> feat: add support for WPGraphQL for WooCommerce

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-headless-login.php
> release: 0.0.4

- CHANGELOG.md
- composer.lock
- src/Auth/Auth.php
- src/Auth/ProviderConfig/OAuth2/Generic.php
- src/Auth/ProviderConfig/OAuth2/OAuth2Config.php
- src/Auth/ProviderConfig/SiteToken.php
- src/Mutation/LinkUserIdentity.php
- tests/wpunit/CoreSchemaFiltersTest.php
- tests/wpunit/ProviderMutationsFacebookTest.php
- tests/wpunit/ProviderMutationsGenericTest.php
- tests/wpunit/ProviderMutationsGithubTest.php
- tests/wpunit/ProviderMutationsGoogleTest.php
- tests/wpunit/ProviderMutationsInstagramTest.php
- tests/wpunit/ProviderMutationsLinkedInTest.php
- tests/wpunit/ProviderMutationsPasswordTest.php
- tests/wpunit/ProviderMutationsSiteTokenTest.php
- tests/wpunit/SettingsTest.php
- vendor/composer/installed.php
Backfills tests, fixing several issues along the way.
Closes #8
See commit log.
> tests: backfill

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- phpstan/constants.php
- readme.txt
- src/Auth/Request.php
- vendor/composer/installed.php
- wp-graphql-headless-login.php
Version bump.
Also fixes a PHP notice.
> release: 0.0.7

- CHANGELOG.md
- README.md
- docs/recipes/client-side-auth-nextauth.md
- docs/recipes/server-side-auth-next-api-routes.md
Adds an example to the documentation for using the `SiteToken` and `Password` provider mutations with NextAuth.js
Closes #58 
(With lots of warnings about the risks of using the `SiteToken` to force-auth).
> dev: add example for NextAuth.js usage

- CHANGELOG.md
- README.md
- composer.lock
- docs/recipes/server-side-auth-next-api-routes.md
- package-lock.json
- package.json
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-headless-login.php
Version bump.
Also update composer dev-deps.
SemVer 🔥
Requires #70
> release: v0.1.0

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
Fixes typos in the GitHub issue templates.
> chore: fix typos in issue templates

- CHANGELOG.md
- README.md
- docs/recipes/server-side-auth-next-api-routes.md
Updates the recipe for NextJS + Server Side Auth, per the feedback from the WPEBuilders livestream and the live code sample, and add links to the AxePress Playground demo branch.
> docs: update server-side example + demo

- CHANGELOG.md
- src/Auth/ProviderConfig/OAuth2/Facebook.php
- src/Auth/ProviderConfig/OAuth2/Generic.php
- src/Model/Client.php
- src/WoocommerceSchemaFilters.php
This PR makes anonymous functions `static` whenever possible.
Anonymous functions pass the class instance, even if its not necessary, which can cause issues with garbage collection.
See https://core.trac.wordpress.org/ticket/58323
> dev: make anonymous functions static

- CHANGELOG.md
- README.md
- package.json
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-headless-login.php
> chore: version bump

- .github/workflows/code-quality.yml
- .github/workflows/schema-linter.yml
- .github/workflows/upload-schema-artifact.yml
- .phpcs.xml.dist
- CHANGELOG.md
- bin/run-docker.sh
- composer.lock
- docker-compose.yml
- phpstan.neon.dist
- readme.txt
- src/Admin/Settings.php
- src/Auth/ProviderConfig/OAuth2/OAuth2Config.php
- vendor-prefixed/firebase/php-jwt/src/CachedKeySet.php
- vendor-prefixed/firebase/php-jwt/src/JWK.php
- vendor-prefixed/firebase/php-jwt/src/JWT.php
- vendor/composer/installed.json
- vendor/composer/installed.php
Updates the composer deps, bumps the suggested WP test version to 6.2 and stans/lints.
> chore: update deps

- CHANGELOG.md
- docs/reference/actions.md
- docs/reference/filters.md
- src/Auth/Auth.php
- src/Auth/Client.php
This PR adds the following Actions/Filters to the plugin:
- `graphql_login_authenticated_user_data`: Filters the user data returned by the Provider, before it is used to match/create the user.
- `graphql_login_after_authenticate`:  Triggers after a user is authenticated by the Provider.
- `graphql_login_pre_get_user_from_data`: Lets you shortcircut the user-matching logic.
- `graphql_login_get_user_from_data`: Fires after the WordPress User has been matched.
- `graphql_login_create_user_data` : Filters the provider data used to create a new WordPress user when no match is found.
Additionally: this PR fixes an issue with `graphql_login_after_successful_login`, where the `WP_User` was being passed twice, instead of the user data from the provider. Props @martinowren in #83
These …
> dev: add new `actions/filters to Client class

- .github/workflows/integration-testing.yml
- CHANGELOG.md
- bin/run-docker.sh
- docker-compose.yml
- readme.txt
- wp-graphql-headless-login.php
Tests against WordPress's latest and greatest.
> ci: test against WP 6.4.1

- docs/core-concepts/how-it-works.md
- docs/recipes/client-side-auth-nextauth.md
- Reordering numbers
- Added missing `.`
> docs: fix typo

- .gitattributes
- CHANGELOG.md
- codeception.dist.yml
- composer.json
- phpstan.neon.dist
- src/Autoloader.php
This PR cherry-picks the general cleanup changes from #100 
Specifically:
- Some CI config files ( `.gitattributes`, `codeception.dist.yml`) have been cleaned up.
- `Autoloader` class has been refactored for DRYness.
> chore: cherry-pick from #100 

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-headless-login.php
> release: v0.2.0

- .github/workflows/code-quality.yml
- .github/workflows/code-standard.yml
- .github/workflows/integration-testing.yml
- .github/workflows/schema-linter.yml
- .github/workflows/upload-release.yml
- .github/workflows/upload-schema-artifact.yml
- CHANGELOG.md
- bin/run-docker.sh
- docker-compose.yml
- readme.txt
- wp-graphql-headless-login.php
This PR updates the GitHub Workflows, and tests the plugin against WordPress 6.5
> ci: update GH workflows and test against WP 6.5

- CHANGELOG.md
- composer.json
- composer.lock
- phpstan.neon.dist
- phpstan/constants.php
- src/Admin/Settings.php
- src/Admin/Settings/AccessControlSettings.php
- src/Admin/Settings/PluginSettings.php
- src/Admin/Settings/ProviderSettings.php
- src/Auth/Auth.php
- src/Auth/Client.php
- src/Auth/ProviderConfig/OAuth2/Google.php
- src/Auth/ProviderConfig/OAuth2/OAuth2Config.php
- src/Auth/ProviderConfig/Password.php
- src/Auth/ProviderConfig/ProviderConfig.php
- src/Auth/ProviderConfig/ProviderConfigStaticTrait.php
- src/Auth/ProviderConfig/SiteToken.php
- src/Auth/ProviderRegistry.php
- src/Auth/Request.php
- src/Auth/TokenManager.php
- src/Auth/User.php
- src/Type/WPInterface/ClientOptions.php
- src/Type/WPInterface/LoginOptions.php
- src/Utils/Utils.php
- vendor/composer/installed.php
- wp-graphql-headless-login.php
This PR implements stricter PHPStan rules, and fixes the resulting type errors.
Formatting issues regarding traversable array types have been fixed as well.
> chore: implement PHPStan strict rules and fix type errors.

- CHANGELOG.md
- composer.json
> ci: Update Strauss to v0.17.0

- CHANGELOG.md
- activation.php
- deactivation.php
- src/Autoloader.php
- src/Main.php
- vendor/composer/installed.php
- wp-graphql-headless-login.php
This PR namespaces the root PHP files (`wp-graphql-headless-login.php`, `activation.php`, `deactivation.php`) with `WPGraphQL\Login`, and cleans up the classes as a result.
> chore: cleanup plugin instantiation

- CHANGELOG.md
- README.md
- package.json
- phpstan/constants.php
- readme.txt
- wp-graphql-headless-login.php
> release: 0.3.0

- composer.lock
- vendor/composer/installed.php
Updates Composer dev-deps to thier latest (semver compatible) versions
PHPStan 1.12.0
> chore: update Composer dev-deps

- .github/workflows/integration-testing.yml
- CHANGELOG.md
- bin/run-docker.sh
- docker-compose.yml
- readme.txt
- wp-graphql-headless-login.php
Explicitly tests compatibility against WordPress 6.6
> ci: test WP 6.6

- .github/workflows/integration-testing.yml
- CHANGELOG.md
- bin/build-docker.sh
- readme.txt
- wp-graphql-headless-login.php
Adds compatibility testing against WP 6.7
> ci: test against WP 6.7

- packages/admin/components/fields/field-control.tsx
- packages/admin/components/fields/field.tsx
- packages/admin/components/fields/index.tsx
- packages/admin/components/provider-config/ClientPanel.tsx
- packages/admin/components/screen/screen.tsx
- packages/admin/components/screen/setting-screen.tsx
- packages/admin/contexts/settings-context.tsx
This PR implements frontend checking for `conditionalLogic` defined by the schema.
Follow up to #144
> dev: check conditional logic on frontend settings

- CHANGELOG.md
- packages/admin/components/layout/header/advanced-settings-toggle/index.tsx
- packages/admin/contexts/settings-context.tsx
- src/Admin/Settings.php
- src/Admin/Settings/AbstractSettings.php
- src/Admin/Upgrade/AbstractUpgrade.php
- src/Admin/Upgrade/UpgradeRegistry.php
- src/Admin/Upgrade/V0_4_0.php
- src/Utils/Utils.php
- tests/wpunit/UpgradeTest.php
Backported from #129
This PR contains miscelaneous fixes on the currently `develop` branch, discovered during work on #129 .
They relate to necessary functionality for #129 that was merged previously in this release cycle. now that #129 is closer to merge, it is surfacing edge cases which we don't want to be polluted by the other PR.
> dev: misc fixes

- .github/workflows/codeception.yml
- .github/workflows/package-linter.yml
- .github/workflows/phpcs.yml
- .github/workflows/phpstan.yml
- .github/workflows/schema-linter.yml
- CHANGELOG.md
- bin/install-test-env.sh
> ci: fix flakiness with `wp core download`

- CHANGELOG.md
- docs/recipes/provider-config.md
- src/Auth/ProviderConfig/OAuth2/GitHub.php
Updates the link for GitHub's list of available scopes to https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes
The old link went stale: https://github.com/AxeWP/wp-graphql-headless-login/discussions/163
> chore: Update help link for GitHub's list of available scopes

- CHANGELOG.md
- wp-graphql-headless-login.php
This PR fixes the call to `register_deactivation_hook()`
Because it was previously calling `register_activation_hook()` instead.
> fix: Correctly load deactivation hook.

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- phpstan/constants.php
- readme.txt
- wp-graphql-headless-login.php
> release: 0.4.2

- .phpcs.xml.dist
- CHANGELOG.md
- composer.lock
- src/Auth/ProviderConfig/OAuth2/OAuth2Config.php
- src/Auth/Request.php
- tests/wpunit/AccessFunctionsTest.php
- tests/wpunit/RequestTest.php
This PR fixes a bug where origins with the same host were being compared and returned incorrectly.
- Fixes #169 
If a host matches:
1. _IF_ a port is specified in the allowed origin, then a port comparison is made.
2. When a domain is matched, the _request_ origin is returned instead of the response origin, allowing for graceful wildcard matches.
> fix: Compare ports when validating allowed origins.
