CHANGELOG.md, README.md, wp-graphql-headless-login.php
Improves checks for plugin requirements, by reporting incompatible versions (WPGraphQL < v1.12.0 ) and incompatible plugins (WP GraphQL JWT Authentication), while allowing core functions to be overloaded.
- feat: Improve requirement checks for `WPGraphQL` (required:v1.12.0) and `WPGraphQL-JWT-Authentication`(conflicted) plugins.
- dev: Allow core function overloading in `wp-graphql-headless-login.php`.
=> feat: better plugin requirement checking

CHANGELOG.md, src/Auth/Auth.php, src/Mutation/LoginWithPassword.php
This pr calls `do_action( 'wp_login' )` after the user is successfully set. 
Usually that action is called by `wp_signon()`, which we dont call.
=> dev: trigger `wp_login` action on successful login

src/Auth/ProviderConfig/ProviderConfigStaticTrait.php
Adds `useAuthenticationCookie` GraphQL field to `LoginOptions`.
This was unintentionally excluded from #28
=> dev: expose `useAuthenticationCookie` to schema

CHANGELOG.md, src/CoreSchemaFilters.php
This PR changes the conditional for adding tokens to the header response to use `WPGraphQL::debug()` instead of the `GRAPHQL_DEBUG` constant.
So headers can be sent when using the backend setting or WP filter to set WPGraphQL debugging.
=> fix: use WPGraphQL::debug() over `GRAPHQL_DEBUG` constant when adding headers

CHANGELOG.md, deactivation.php, src/Model/User.php, src/Mutation/LoginWithPassword.php, src/Utils/Utils.php
This PR refactors the code using `graphql_get_login_setting()` to check for a value's truthiness
`get_option()` returns strings instead of scalars like `true` and `false`, which caused strict checks to fail.
=> fix: check for truthy values when using `graphql_get_login_setting()`

src/Type/WPObject/AuthenticationData.php
Tries to coerce non-core Models into a `Model\User` when resolving for `AuthenticationData`
Fixes an oversight in #30 :
The WooGraphQL `customer` model doesn't extend the `User`, and this generic shim seems like the best approach to supporting other custom types defined by the `graphql_login_user_types` filter.
=> fix: get `User` model when resolving custom user type

CHANGELOG.md, src/CoreSchemaFilters.php
This PR fixes a bug where adding the `X-WPGraphQL-Login-Refresh-Token` to `Access-Control-Expose-Headers` would overwrite existing values.
=> fix: Don't overwrite existing `Access-Control-Expose-Headers` when adding `X-WPGraphQL-Login-Refresh-Token`.

.phpcs.xml.dist, CHANGELOG.md, composer.lock, vendor/composer/installed.php
Fixes the phpcs ruleset to correctly lint againt WP 5.6
=> chore: (PHPCS) set `minimum_supported_wp_version` to 5.6

src/Auth/Request.php, tests/functional/AuthenticatedQueryCest.php, tests/wpunit/RequestTest.php
This PR refines #45 by refactoring the way the request headers are sent.
Specifically:
- The `Vary: Origin` header is now set if there are multiple possible allowed origins for the request.
- `X-WPGraphQL-Login-Token` is now included in `Access-Control-Allow-Headers` and excluded from `Access-Control-Expose-Headers`.
- `X-WPGraphQL-Login-Refresh-Token` is now only included in `Access-Control-Expose-Headers` if a valid refresh token is returned in the response.
=> dev: fix and refine request headers logic

CHANGELOG.md, src/Auth/ProviderConfig/SiteToken.php, src/Auth/ProviderRegistry.php, src/Auth/Request.php, src/Mutation/Login.php, tests/functional/SiteTokenAuthenticationCest.php, tests/wpunit/RequestTest.php, tests/wpunit/SiteTokenProviderMutationsTest.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php, vendor/composer/installed.php
This PR adds the Site Token provider, which allows to frontend to use a special header secret to authenticate as _any_ user.
Due to the security implications, the secret should only be added to the header on a server-side request.
To allow easy integration with frontend-first authentication strategies (e.g NextAuth).
1. User enables the Site Token provider, sets the name of the custom header, the secret key to use, and the user field to use for the identity lookup.
2. The user authenticates with their frontend provider, and uses the returned subject identity in a *server site graphql request*, with the secret set on the header.
=> feat: add Site Token provider

CHANGELOG.md, docs/mutations.md, src/Auth/ProviderConfig/OAuth2/Generic.php, src/Auth/ProviderRegistry.php, src/Utils/Utils.php, tests/wpunit/ProviderMutationsGenericTest.php
Changes the `ProviderRegistery` to use `ProviderConfig::get_slug()` for the provider class keys. This ensures the code will continue to work even if the slug of a `ProviderConfig` gets changed in the future.
Fixes #56 
(caused by the slug for OAuth2 Generic changing in v0.0.7)
=> fix!: use ProviderConfig::get_slug() for registry keys

CHANGELOG.md, src/Admin/UserProfile.php
Use `TokenManager::refresh_user_secret()` when revoking secrets on the backend.
Since `TokenManager::revoke_user_secret()` leaves no secret set, this would cause a fatal GraphQL error, instead of a request for reauthorization.
- fix: Use `TokenManager::refresh_user_secret()` when revoking secrets on the backend to prevent `UserError`s for invalid secrets.
=> fix: use refresh_user_secret() when revoking on backend

CHANGELOG.md, src/Admin/UserProfile.php
This PR removes the `Password` provider from the list of Identities on the User Profile page.
The password provider is self referencing.
=> fix: hide Password provider from User Profile identities list.

.github/workflows/integration-testing.yml, CHANGELOG.md, readme.txt, wp-graphql-headless-login.php
Tests the plugin against the latest version of WordPress.
Also removes extension testing from v5.9
WC now only supports >6.0
=> ci: test plugin against 6.2

CHANGELOG.md, wp-graphql-headless-login.php
Shows an `admin_notice` about the conflict with WPGraphQL CORS when both plugins are enabled.
We can't maintain compatibility with their header filters, and their plugin includes a conflicting login/logout mechanism that we cannot easily reuse.
=> dev: show conflict notice for WPGraphQL CORS

CHANGELOG.md, docs/recipes/server-side-auth-next-api-routes.md
Fixes the WooGraphQL usage section in the server-side auth docs, to explain the ideal usage.
As pointed out by @kidunot89, the previous example would reset the `woocommerce-session` both when the user logs in, and every time they revalidate.
Changes recommendation to use `woocommerce-session` header from the get go, and calls out the (apparently) **bad** pattern of using `wooSessionToken`.
=> docs: fix woographql example

package-lock.json, package.json
Addresses a regression in #75 where the `@wordpress/core-data` _types_ were removed but the package itself was not added to the NPM dev dependencies.
=> chore: add missing @wordpress/core-data to npm dev-deps

CHANGELOG.md, src/Auth/ProviderConfig/OAuth2/Facebook.php, src/Auth/ProviderConfig/OAuth2/Generic.php, src/Auth/ProviderConfig/OAuth2/Instagram.php
This PR stops imploding the ProviderConfg's `scope` setting array, instead deferring that responsibility to the underlying OAuth2 Provider. Additionally, a new `scopeSeparator` option has been added to the OAuth2 Generic client.
Note: this _does not_ fix the bug where the `Scope` field itself is missing.
@martinowren reported (Slack) that VIPPS uses space separators.
=> fix: use scope separators from Provider library.

CHANGELOG.md, bin/_lib.sh, phpstan/constants.php, src/Auth/ServerAuthentication.php, src/Auth/TokenManager.php, src/Autoloader.php, src/CoreSchemaFilters.php, src/Main.php, tests/wpunit/CoreSchemaFiltersTest.php, tests/wpunit/ServerAuthenticationTest.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php, vendor/composer/installed.php, wp-graphql-headless-login.php
This PR fixes an issue where `determine_current_user` was only being applied after the rest of the plugin is initialized (after 'graphql_init').
External plugins need to check the user's validity, sometimes even before `plugins_loaded`. E.g. https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-session-handler.php#L104-L110
h/t @kidunot89 
The `determine_current_user` filter has been moved from `CoreSchemaFilters` to a new `Auth\ServerAuthentication` class, which is hooked separately from the rest of the plugin initialization.
Additionally, the type requirements of the `$user_id` param have been loosened to allow for better compatibility with external plugins who arent adhering to WP's types, and an instance property has been added to prevent …
=> fix: apply 'determine_current_user' filter before plugin is initialized

CHANGELOG.md, src/Auth/Auth.php, src/WoocommerceSchemaFilters.php
This PR defers the registration of `LoginPayload.customer` to WooGraphQL in v0.18.2+ (tba) which has added explicit support for this plugin.
Similarly, `LoginPayload.wooSessionToken` has been deprecated in favor of the `sessionToken` that WooGraphQL creates (and adds in v0.18.2+)
Ecosystem interoperability.
=> dev: use WooGraphQL 0.18.2 for `LoginPayload` fields

CHANGELOG.md, src/Auth/ProviderConfig/OAuth2/OAuth2Config.php
This PR removes the strict-typing in `OAuth2Config` for `\WPGraphQL\Login\Vendor\League\OAuth2\Client\Provider\AbstractProvider`. PHPDoc hints are used instead.
Closes #106
=> fix: Avoid strict-typing `League\OAuth2\Client\Provider\AbstractProvider` to the `\WPGraphQL\Login\Vendor` namespace.

CHANGELOG.md, docs/reference/mutations.md, src/Mutation/RefreshToken.php, tests/wpunit/RefreshTokenMutationTest.php
This PR adds the `authTokenExpiration` field to the `refreshToken` mutation payload.
API oversight, flagged by @richardaubin in [Slack](https://wp-graphql.slack.com/archives/C05BDQ376LA/p1707115150279189?thread_ts=1706550831.628589&cid=C05BDQ376LA)
```graphql
mutation refreshToken(
$token: String! # The user's refreshToken.
) {
refreshToken( input: {refreshToken: $token} ) {
authToken
authTokenExpiration # 👈
success
}
}
```
=> feat: expose `refreshToken.authTokenExpiration`

CHANGELOG.md, bin/run-docker.sh, composer.json
Replaces calls to `docker-compose` with `docker compose`.
The old commands are no longer included in the GH runner.
=> chore: update `docker-compose` commands to `docker compose`

packages/admin/components/fields/field-control.tsx
This PR updates the Field Control components to use the `defaultValue` if no field value is explicitly set.
Backported from #129 . Props @alexookah
=> fix: use `defaultValue` in field control

src/Admin/Settings/AbstractSettings.php
Fixes the `Setting.controlType` phpstan definition
=> chore: fix `Setting.controlType` allowed values [PHPStan]

packages/admin/components/fields/index.tsx, packages/admin/components/layout/header/menu/index.tsx, packages/admin/components/screen/context.tsx, packages/admin/components/screen/screen.tsx, packages/admin/components/screen/setting-screen.tsx, packages/admin/components/screen/utils.ts, packages/admin/contexts/settings-context.tsx, packages/admin/types.d.ts, src/Admin/Settings/AbstractSettings.php, src/Admin/Settings/AccessControlSettings.php, src/Admin/Settings/PluginSettings.php
This PR refactors the frontend package to source the screen titles, menu label, and descriptions from the server via the `wpGraphQLLogin.settings` global.
So new settings don't need to be manually allow-listed.
Provider screen is still manually hydrated until that component gets refactored.
=> dev: source setting screens from global

composer.json, composer.lock, phpstan.neon.dist, src/Admin/SettingsRegistry.php, src/Auth/ProviderRegistry.php, src/Model/Client.php, src/Model/User.php
Bumps PHPStan and PHPStan-WordPress to v2.0.x, and remediates the surfaced sniffs.
=> chore: bump PHPStan to v2.x
